version: '3.0'
services:
  pg_rss_reader:
    image: docker.bale.ai/money/balepostgres:1.6.0
    container_name: pg_rss_reader
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=my_db
      - TZ=Asia/Tehran
    volumes:
      - /home/docker/volumes/pg_rss_reade1r/postgres/:/var/lib/postgresql/data/

  rss_reader:
    image: docker.bale.ai/money/rss_reader:0.10-12
    container_name: rss_reader
    environment:
      #   PostgreSQL Config
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123456
      - POSTGRES_DB=my_db
      - POSTGRES_HOST=pg_rss_reader
      - POSTGRES_PORT=5432
      #   Config
      - BASE_URL=https://tapi.bale.ai/
      - BASE_FILE_URL=https://tapi.bale.ai/file/
      - TOKEN=2063839091:6fcac9a53e5a7cbcd7e2c71abfcdba3d4c5ece88
      - RSS_INTERVAL=5
      - RSS_COUNT=4
      - POLL_INTERVAL=0.5
    restart: always # use always
    depends_on:
      - pg_rss_reader